version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: listie
      POSTGRES_PASSWORD: "2Jf4_qjfzb-hdJmzOgHSp-FCcwHa7hEL"
    volumes:
      - listie_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "Z8nOrrBcRC63L5tXzp5oUnAjEV4xv59u"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  listie_data:
